### ISSUE TITLE
feedly网页版适配

### ISSUE THREAD

**Issue by SuZixiong** [scarsty/FontChineseYahei#1]
你好，您的开发的Chrome扩展是我适用下来最好的。
但是有一个小小的Bug，那就是feedly网页版并没有适配为雅黑。
请问能解决一下吗？
谢谢！具体查看下图。
![qq 20160413123058](https://cloud.githubusercontent.com/assets/4355746/14482846/9cc30188-0173-11e6-9ab9-91f193f69c43.jpg)

**Comment by scarsty** [comment]
这个网站我不会用。你可以用 what's font 查看一下他们用的是什么字体

**Comment by SuZixiong** [comment]
中英文的字体都是 sans-serif font

**Comment by scarsty** [comment]
你先把chrome默认的无衬线字体换成雅黑试试。

**Comment by SuZixiong** [comment]
可以了，将设置中的sans-serif改为微软雅黑之后feedly网页中的字体全部现在为微软雅黑了。
多谢！
