### ISSUE TITLE
冒昧咨询下

### ISSUE THREAD

**Issue by nanalian** [scarsty/FontChineseYahei#3]
之前看到您在0.7.54.29已提供苹方字体的支持。所以作为使用者向冒昧咨询下，如何调整各类字体替换的优先级。我的邮箱地址是nanalian@gmail.com，希望您可以在百忙之中抽空答复下，谢谢您。

**Comment by scarsty** [comment]
在css里面把顺序改掉就可以了。

**Comment by nanalian** [comment]
我明白了，就是2yahei.css这个文件是吧，谢谢您。
