### ISSUE TITLE
如何屏蔽掉控制台中的提示信息?

### ISSUE THREAD

**Issue by reuwi** [scarsty/FontChineseYahei#6]
貌似在网速不好的情况下控制台会有以下提示信息:
Slow network is detected. Fallback font will be used while loading:

对于经常需要看控制台调试的前端来说这些提示信息很干扰调试,请问如何关掉呢?或者可以设置在特定网站上不启用该插件吗?

**Comment by scarsty** [comment]
这个我也不知道
